### ISSUE TITLE
Configuration File Location?

### ISSUE THREAD

**Issue by Stenstromen** [passbolt/go-passbolt-cli#16]
When configure is first run

Example:
`passbolt configure --serverAddress https://passbolt.example.org --userPassword '1234' --userPrivateKeyFile 'keys/privatekey.asc'`

Where is the local configuration file stored?

**Comment by speatzle** [comment]
By default, a subfolder for go-passbolt-cli is created in your OS's Application Configuration Folder in which the config file is created.

To determine this Folder Go's  "os.UserConfigDir" is used. Its Documentation States:

> On Unix systems, it returns $XDG_CONFIG_HOME as specified by https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html if non-empty, else $HOME/.config. On Darwin, it returns $HOME/Library/Application Support. On Windows, it returns %AppData%. On Plan 9, it returns $home/lib.

So on Linux it would Typically be `~/.config/go-passbolt-cli/go-passbolt-cli.toml`.

Since this config contains sensitive information it uses a 600 Permission Mask.

You can override this location using the `--config` parameter.

You can see the logic [here](https://github.com/passbolt/go-passbolt-cli/blob/2b52c420c4ad3cc5501263da3dfa12caacbcc7e8/cmd/root.go#L69).

**Comment by Stenstromen** [comment]
Thank you @speatzle for the quick response.

I installed go-passbolt-cli on MacOS using go and couldn't find anything in my $HOME.

So i did a `~$ find / -name go-passbolt-cli` and can you guess where i found the go-passbolt-cli.toml?..

In `/System/Volumes/Data/Users/$USER/Library/Application Support/go-passbolt-cli/go-passbolt-cli.toml` of all places...

Thanks again.

**Comment by cueedee** [comment]
@Stenstromen, that path is the long form for `~/Library/Application\ Support/go-passbolt-cli/go-passbolt-cli.toml`.

What scared me though, is seeing that this just stores both the `userprivatekey` and its passphrase in plaintext. The file appears to have mode `0600` by default, so by understatement it's not blatantly unsafe, but still...

At least the [javascript client](/passbolt/passbolt_cli) just relied on proven`gpg` architecture to manage this stuff.

**Comment by speatzle** [comment]
Hey @cueedee,
go-passbolt-cli is "just" a wrapper around go-passbolt and in the beginning was for testing go-passbolt but evolved over time into a usable project.

Since go-passbolt is made to be portable and not depend on anything external, go-passbolt-cli can't really use gnupg without major modifications.

From what i have seen, go-passbolt-cli is mostly used in scripts without any direct user interaction which means that the Script or go-passbolt-cli need to be able to retrieve the Private Key and Password by themself in which case "gpg infrastructure" is just as safe as a file that only the user can access.

You can also just store the Private Key without the Password and go-passbolt-cli will Prompt you for the Password each time, the same applies to MFA. The Passbolt Browser Extension also just stores the Private Key in the Browser, so the Security level is the exact same in that case.

Using the Config is completely optional as stated in the README.md and you can instead specify everything using Environment Variable or Flags Instead.

As such i don't see how this is unsafe.
