### ISSUE TITLE
export to keepass with user + password + TOTP not possible  

### ISSUE THREAD

**Issue by frankdox** [passbolt/go-passbolt-cli#42]
**Describe the bug:**
after using the new TOTP feature in passbolt the export to keepass is no longer possible

**To Reproduce:**
1. use credentials with TOTP entry
2. start passbolt export keepass

**Output**
Error: Get Resource 62, bbbbbbbb-cccc-1111-8a8a-badeaffe032 Unknown ResourceType: password-description-totp

**Passbolt Server Version  (please complete the following information):**
 - Edition: PRO
 - Version 4.4.0

**go-passbolt-cli Version (please complete the following information):**
 - OS: linux
 - Version 0.2.0 via apt

**Additional context**
-

**Comment by speatzle** [comment]
Hi, currently go-passbolt-cli does not support passwords with a TOTP, i have started the work to support TOTP Resources in go-passbolt a while ago https://github.com/passbolt/go-passbolt/commit/8dbb07720dbbb76a099d97d151c385514e251705 but haven't had the Time to finish it up in go-passbolt-cli since it needs a bunch of new functionality to display and modify them, ill see if i can't add basic support for the Resource Type soon but can't Promise anything.

**Comment by speatzle** [comment]
Hi @frankdox I have made a PR which has Support for TOTP Export and Skipping Resources on Error, If you can please pull the branch, compile and Test if it works for you, i have been able to see one of my TOTP's in KeepassXC from a export Keepass File.

**Comment by frankdox** [comment]
Hi @speatzle,

i have compiled this branch an tested it successfully in KeepassXC an Strongbox (both OSX) with over 1000 creds. 
Thank you for your support.


🥇

**Comment by speatzle** [comment]
Perfect Ill add a few other things and ill make a new release soon.

**Comment by speatzle** [comment]
Hi, i just released v0.3.1 with these improvements.
